# TCL File Generated by Component Editor 17.1
# Tue Nov 24 19:12:48 CST 2020
# DO NOT MODIFY


# 
# MorseEncoder "MorseEncoder" v1.0
#  2020.11.24.19:12:48
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module MorseEncoder
# 
set_module_property DESCRIPTION ""
set_module_property NAME MorseEncoder
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME MorseEncoder
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL MorseEncoder
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file MorseEncoder.sv SYSTEM_VERILOG PATH MorseEncoder.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter IDLE STD_LOGIC_VECTOR 0
set_parameter_property IDLE DEFAULT_VALUE 0
set_parameter_property IDLE DISPLAY_NAME IDLE
set_parameter_property IDLE WIDTH 4
set_parameter_property IDLE TYPE STD_LOGIC_VECTOR
set_parameter_property IDLE UNITS None
set_parameter_property IDLE ALLOWED_RANGES 0:15
set_parameter_property IDLE HDL_PARAMETER true
add_parameter QUEUE_LOAD STD_LOGIC_VECTOR 1
set_parameter_property QUEUE_LOAD DEFAULT_VALUE 1
set_parameter_property QUEUE_LOAD DISPLAY_NAME QUEUE_LOAD
set_parameter_property QUEUE_LOAD WIDTH 4
set_parameter_property QUEUE_LOAD TYPE STD_LOGIC_VECTOR
set_parameter_property QUEUE_LOAD UNITS None
set_parameter_property QUEUE_LOAD ALLOWED_RANGES 0:15
set_parameter_property QUEUE_LOAD HDL_PARAMETER true
add_parameter QUEUE_CHECK STD_LOGIC_VECTOR 2
set_parameter_property QUEUE_CHECK DEFAULT_VALUE 2
set_parameter_property QUEUE_CHECK DISPLAY_NAME QUEUE_CHECK
set_parameter_property QUEUE_CHECK WIDTH 4
set_parameter_property QUEUE_CHECK TYPE STD_LOGIC_VECTOR
set_parameter_property QUEUE_CHECK UNITS None
set_parameter_property QUEUE_CHECK ALLOWED_RANGES 0:15
set_parameter_property QUEUE_CHECK HDL_PARAMETER true
add_parameter DOT STD_LOGIC_VECTOR 3
set_parameter_property DOT DEFAULT_VALUE 3
set_parameter_property DOT DISPLAY_NAME DOT
set_parameter_property DOT WIDTH 4
set_parameter_property DOT TYPE STD_LOGIC_VECTOR
set_parameter_property DOT UNITS None
set_parameter_property DOT ALLOWED_RANGES 0:15
set_parameter_property DOT HDL_PARAMETER true
add_parameter DASH STD_LOGIC_VECTOR 4
set_parameter_property DASH DEFAULT_VALUE 4
set_parameter_property DASH DISPLAY_NAME DASH
set_parameter_property DASH WIDTH 4
set_parameter_property DASH TYPE STD_LOGIC_VECTOR
set_parameter_property DASH UNITS None
set_parameter_property DASH ALLOWED_RANGES 0:15
set_parameter_property DASH HDL_PARAMETER true
add_parameter SHORT_DELAY STD_LOGIC_VECTOR 5
set_parameter_property SHORT_DELAY DEFAULT_VALUE 5
set_parameter_property SHORT_DELAY DISPLAY_NAME SHORT_DELAY
set_parameter_property SHORT_DELAY WIDTH 4
set_parameter_property SHORT_DELAY TYPE STD_LOGIC_VECTOR
set_parameter_property SHORT_DELAY UNITS None
set_parameter_property SHORT_DELAY ALLOWED_RANGES 0:15
set_parameter_property SHORT_DELAY HDL_PARAMETER true
add_parameter LONG_DELAY STD_LOGIC_VECTOR 6
set_parameter_property LONG_DELAY DEFAULT_VALUE 6
set_parameter_property LONG_DELAY DISPLAY_NAME LONG_DELAY
set_parameter_property LONG_DELAY WIDTH 4
set_parameter_property LONG_DELAY TYPE STD_LOGIC_VECTOR
set_parameter_property LONG_DELAY UNITS None
set_parameter_property LONG_DELAY ALLOWED_RANGES 0:15
set_parameter_property LONG_DELAY HDL_PARAMETER true
add_parameter FINISH STD_LOGIC_VECTOR 7
set_parameter_property FINISH DEFAULT_VALUE 7
set_parameter_property FINISH DISPLAY_NAME FINISH
set_parameter_property FINISH WIDTH 4
set_parameter_property FINISH TYPE STD_LOGIC_VECTOR
set_parameter_property FINISH UNITS None
set_parameter_property FINISH ALLOWED_RANGES 0:15
set_parameter_property FINISH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 5
add_interface_port avalon_slave_0 read_data readdata Output 8
add_interface_port avalon_slave_0 write_data writedata Input 8
add_interface_port avalon_slave_0 write_enable write Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset reset_sink
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end leds write Output 7

