# TCL File Generated by Component Editor 17.1
# Thu Nov 26 19:01:16 CST 2020
# DO NOT MODIFY


# 
# MorseDecoder "MorseDecoder" v1.0
#  2020.11.26.19:01:16
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module MorseDecoder
# 
set_module_property DESCRIPTION ""
set_module_property NAME MorseDecoder
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME MorseDecoder
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL MorseDecoder2
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file MorseDecoder2.sv SYSTEM_VERILOG PATH MorseDecoder2.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter IDLE STD_LOGIC_VECTOR 0
set_parameter_property IDLE DEFAULT_VALUE 0
set_parameter_property IDLE DISPLAY_NAME IDLE
set_parameter_property IDLE WIDTH 5
set_parameter_property IDLE TYPE STD_LOGIC_VECTOR
set_parameter_property IDLE UNITS None
set_parameter_property IDLE ALLOWED_RANGES 0:31
set_parameter_property IDLE HDL_PARAMETER true
add_parameter DOT_ST STD_LOGIC_VECTOR 1
set_parameter_property DOT_ST DEFAULT_VALUE 1
set_parameter_property DOT_ST DISPLAY_NAME DOT_ST
set_parameter_property DOT_ST WIDTH 5
set_parameter_property DOT_ST TYPE STD_LOGIC_VECTOR
set_parameter_property DOT_ST UNITS None
set_parameter_property DOT_ST ALLOWED_RANGES 0:31
set_parameter_property DOT_ST HDL_PARAMETER true
add_parameter WAIT_DOT_RELEASE STD_LOGIC_VECTOR 2
set_parameter_property WAIT_DOT_RELEASE DEFAULT_VALUE 2
set_parameter_property WAIT_DOT_RELEASE DISPLAY_NAME WAIT_DOT_RELEASE
set_parameter_property WAIT_DOT_RELEASE WIDTH 5
set_parameter_property WAIT_DOT_RELEASE TYPE STD_LOGIC_VECTOR
set_parameter_property WAIT_DOT_RELEASE UNITS None
set_parameter_property WAIT_DOT_RELEASE ALLOWED_RANGES 0:31
set_parameter_property WAIT_DOT_RELEASE HDL_PARAMETER true
add_parameter DASH_ST STD_LOGIC_VECTOR 3
set_parameter_property DASH_ST DEFAULT_VALUE 3
set_parameter_property DASH_ST DISPLAY_NAME DASH_ST
set_parameter_property DASH_ST WIDTH 5
set_parameter_property DASH_ST TYPE STD_LOGIC_VECTOR
set_parameter_property DASH_ST UNITS None
set_parameter_property DASH_ST ALLOWED_RANGES 0:31
set_parameter_property DASH_ST HDL_PARAMETER true
add_parameter WAIT_DASH_RELEASE STD_LOGIC_VECTOR 4
set_parameter_property WAIT_DASH_RELEASE DEFAULT_VALUE 4
set_parameter_property WAIT_DASH_RELEASE DISPLAY_NAME WAIT_DASH_RELEASE
set_parameter_property WAIT_DASH_RELEASE WIDTH 5
set_parameter_property WAIT_DASH_RELEASE TYPE STD_LOGIC_VECTOR
set_parameter_property WAIT_DASH_RELEASE UNITS None
set_parameter_property WAIT_DASH_RELEASE ALLOWED_RANGES 0:31
set_parameter_property WAIT_DASH_RELEASE HDL_PARAMETER true
add_parameter DONE_ST STD_LOGIC_VECTOR 5
set_parameter_property DONE_ST DEFAULT_VALUE 5
set_parameter_property DONE_ST DISPLAY_NAME DONE_ST
set_parameter_property DONE_ST WIDTH 5
set_parameter_property DONE_ST TYPE STD_LOGIC_VECTOR
set_parameter_property DONE_ST UNITS None
set_parameter_property DONE_ST ALLOWED_RANGES 0:31
set_parameter_property DONE_ST HDL_PARAMETER true
add_parameter WAIT_DONE_RELEASE STD_LOGIC_VECTOR 6
set_parameter_property WAIT_DONE_RELEASE DEFAULT_VALUE 6
set_parameter_property WAIT_DONE_RELEASE DISPLAY_NAME WAIT_DONE_RELEASE
set_parameter_property WAIT_DONE_RELEASE WIDTH 5
set_parameter_property WAIT_DONE_RELEASE TYPE STD_LOGIC_VECTOR
set_parameter_property WAIT_DONE_RELEASE UNITS None
set_parameter_property WAIT_DONE_RELEASE ALLOWED_RANGES 0:31
set_parameter_property WAIT_DONE_RELEASE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 read_data readdata Output 8
add_interface_port avalon_slave_0 write_data writedata Input 8
add_interface_port avalon_slave_0 write_enable write Input 1
add_interface_port avalon_slave_0 address address Input 2
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end button_in write Input 2


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point conduit_end_1
# 
add_interface conduit_end_1 conduit end
set_interface_property conduit_end_1 associatedClock clock
set_interface_property conduit_end_1 associatedReset ""
set_interface_property conduit_end_1 ENABLED true
set_interface_property conduit_end_1 EXPORT_OF ""
set_interface_property conduit_end_1 PORT_NAME_MAP ""
set_interface_property conduit_end_1 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_1 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_1 switch_in write Input 4

